### ISSUE TITLE
Plugin cannot be found in standard repositories

### ISSUE THREAD

**Issue by aweinert** [vbmacher/cup-maven-plugin#1]
When I try to include the plugin in a maven build as suggested by the README, I receive the following error during the build-phase:

```
Downloading: http://repo.maven.apache.org/maven2/edu/tum/cs/cup-maven-plugin/1.0.0/cup-maven-plugin-1.0.0.pom
[WARNING] The POM for edu.tum.cs:cup-maven-plugin:jar:1.0.0 is missing, no dependency information available
```

The relevant part of my `pom.xml` looks as follows:

```
<plugin>
  <groupId>de.jflex</groupId>
  <artifactId>cup-maven-plugin</artifactId>
  <version>1.0.0</version>
  <executions>
    <execution>
      <phase>generate-sources</phase>
      <goals>
        <goal>generate</goal>
      </goals>
      <configuration>
        <cupDefinition>src/main/java/net/alexweinert/coolc/parser/cool.cup</cupDefinition>
        <packageName>net.alexweinert.coolc.parser</packageName>
        <className>Parser</className>
        <outputDirectory>src/main/java/</outputDirectory>
      </configuration>
    </execution>
  </executions>
</plugin>
```

A quick search also does not show the plugin on `maven-repository.com` or `http://mvnrepository.com`.

**Comment by vbmacher** [comment]
Hey there. It's true, the plug-in is not at those places. You can use the following repository, which I use for my projects:

```
    <repository>
      <id>emustudio-repository</id>
      <name>emuStudio Repository</name>
      <url>http://emustudio.sf.net/repository/</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
```

Uploading to central maven repo needs some extra work, according to http://maven.apache.org/guides/mini/guide-central-repository-upload.html. Since I used it for myself, I didn't do the steps. Actually, in the present time, I have found other plug-in which might be already in the Maven central, but I didn't try:

http://czt.sourceforge.net/dev/cup-maven-plugin/
