### ISSUE TITLE
cup-maven-plugin license question

### ISSUE THREAD

**Issue by sidkshatriya** [vbmacher/cup-maven-plugin#8]
This plugin seems to fulfil an important requirement -- thanks for taking the time to build it!

May I request a clarification on the impact of the plugin's GPL license on projects that use your plugin? So if I'm building a project on another license e.g. MIT and want to use your plugin -- does it have any impact on my project? 

My guess is that since this is a maven plugin it will _not_ have any impact on my project. The code generation is being done by the CUP Parser generator ultimately which does not place any constraints. 

However interaction of GPL with non-GPL is a mine field and your plugin is GPL after all so it _might_ have an impact. https://www.gnu.org/licenses/gpl-faq.en.html is overly complex and things can be interpreted in various ways, potentially.

Might I request you to release this project on a more liberal license e.g. Apache 2 (or if that is not possible, add a clarification/addendum to the license text?)

Also the CUP versions that is currently being used, as I understand, is "0.11b 20150226" -- has this been just downloaded from the tum site or built from source?

**Comment by vbmacher** [comment]
Hello, thanks for the questions. I am not expert at licensing and GPL, but I agree it is a complex topic. 

Basically, all CUP-generated parsers are "product" of CUP, which is itself GPL-like licensed program (see http://www2.cs.tum.edu/projects/cup/licence.php). It does not matter if a MIT-licensed project uses my plugin or not, because the same principle holds - resulting parser is a "product" of GPL-like licensed program (in this case, my plugin calls CUP). So "re-licencing" my plugin won't help.

Generally, if this was a problem, nobody could license their programs written in GCC or other GPL-like compilers or maybe use Linux for commercial purposes.

However, there exist some software which are GPL-like-licensed but using their "products" for commercial purposes is kind of problematic. One example is FFMPEG, see https://www.ffmpeg.org/legal.html (the last question). However I don't know if the "problematic" conditions are same for another free license like MIT.

As I understood it, problems might arise when the software uses some patented algorithms. In this case the whole thing requires some special treatment, and the very suggested action to do is to contact authors of the product, and ask. 

In Europe we don't have software patents (and hope never will) - CUP is now held and owned by TUM (Munchen, Germany). Therefore I think CUP is not using patented "special cases" and can be freely used. But if you have some doubts, it will be good to contact CUP authors.

In general, your project doesn't have to be licensed in GPL if you don't incorporate some GPL-licensed source code in your project.

**Comment by sidkshatriya** [comment]
Thanks for your detailed response. I have some follow up points. You say:

> Basically, all CUP-generated parsers are "product" of CUP, which is itself **GPL-like** licensed program (see http://www2.cs.tum.edu/projects/cup/licence.php). It does not matter if a MIT-licensed project uses my plugin or not, because the same principle holds - resulting parser is a "product" of GPL-like licensed program (in this case, my plugin calls CUP). So "re-licencing" my plugin won't help.

[emphasis mine]

CUP license is "GPL-compatible" and not "GPL-like". There are no copyleft type provisions in the license of CUP at all. In fact, if you look at the license of CUP (http://www2.cs.tum.edu/projects/cup/licence.php) its does not really have many restrictions at all (unlike GPL).

(Its important to make the distinction between "GPL-like" and "GPL-compatible". As an example Apache 2 does not have copyleft like provisions but its "compatible" with GPL v3. Its not compatible with GPLv2 however. https://www.gnu.org/licenses/license-list.en.html#apache2 )

The point I'm making here is that CUP license does _not_ compel you make your plugin GPL. The fact that you choose to do so is entirely your prerogative though. 

Reading http://www2.cs.tum.edu/projects/cup/licence.php it says:

> The portions of CUP output which are hard-coded into the CUP source code are (naturally) covered by this same license, as is the CUP runtime code linked with the generated parser

So you're correct: relicensing the plugin will not change the license under which "[t]he portions of CUP output which are hard-coded into the CUP source code" code is generated. However, the main issue I am concerned about would be any potential impact of the use of your maven cup plugin on the rest of my code (which was not "hard-coded" as mentioned). 

You then say:

> As I understood it, problems might arise when the software uses some patented algorithms. In this case the whole thing requires some special treatment, and the very suggested action to do is to contact authors of the product, and ask.

I'm not really worried about the impact of CUP on my project, rather, your plugin. But, after our discussion, its seems that the plugin would _not_ have an impact (you gave the example of Linux).  Moreover as I dug deeper on this issue -- there are IDEs which are GPL but if you use them to do your coding the code is not covered under the GPL. So if I apply the same principle to your plugin, it should not have any impact on me as I understand it. Also as you point out, as long as I'm not incorporating any GPL source code in my project the project is not GPL.

However, the existence of the concept of the GNU classpath linking exception seems to indicate the matter may have some further subtleties (https://www.gnu.org/software/classpath/license.html and https://en.wikipedia.org/wiki/GPL_linking_exception).

> Linking this library statically or dynamically with other modules is making a combined work based on this library. Thus, the terms and conditions of the GNU General Public License cover the whole combination.

[etc.]

Your plugin embeds CUP jars right? But then you call CUP rather than the other way around and the CUP jar is non GPL. So my understanding is that it should _not_ virally make the "combined work" GPL under the theory of the classpath extension. GPL would only apply for the maven plugin, right? 

But then on your README.md you say:

> Java CUP Maven plug-in + repackaged jars: GPL v2.

Maybe I'm being too pedantic here but you seem to indicate here the cup jars are also GPLv2. Should GPLv2 not only extend to the plugin and not the cup jars? The packaged jars come from the java cup project right?

I do apologize in advance if this licensing question is something that is an unwelcome distraction from your everyday responsibilities. Once again, appreciate your work on this plugin. Thanks for the time you've spent on this question. 

P.S. I love the principles behind GPL but of late it has been causing me lots of grief in terms of understanding all the possible implications :-).

**Comment by sidkshatriya** [comment]
I tried to understand the project a bit deeper to explore possible issues around classpath. As you mention in the README there are three artifacts:

> cup-maven-plugin; a Maven plug-in which wraps Java CUP parser generator.
> java-cup; repackaged java-cup-11b.jar as Maven artifact
> java-cup-runtime; repackaged java-cup-11b-runtime.jar as Maven artifact

These (repackaged) java-cup and java-cup-runtime jars are released by you as GPLv2. Specifically the java-cup-runtime repackaged jar is GPLv2. 

If you are embedding the repackaged runtime jar an end user application you are embedding a GPLv2 jar (of course, all the CUP code _within_ the jar will be under the CUP license) but your "re-package" is GPLv2 as per your README. The very act of linking with the runtime jar which is under GPLv2 (even if most of the code "inside it" is not GPLv2) might cause some issues, licensing wise. Or would it not?

**Comment by vbmacher** [comment]
Hello, thanks for the response, and I am glad that the plugin is useful. Don't need to apologize for the questions - I will reply when I have time. Besides I think this debate is really useful since eventually the problem and the final solution might help us to solve further issues - not only in this specific case and project.  

Thanks for pointing out the difference between GPL-like and GPL-compatible. Didn't know about it.

Also thanks for pointing out the GPL linking exception. As I understood it, the linking exception talks about allowing to incorporate some specified portions of GPL-code into your project (e.g. by static or dynamic linking); code portions which are not marked with this exceptions and are included would need to be GPL.

We should also think about re-licencing itself. The way how it work depends. Generally I think it is possible to do things like "hide" some licence behind the other ("wrapping the licence") but only in case if the wrapped license allows it. For example, one can "wrap" a MIT-license project into a "GPL-like" one. But probably not the way around, and we must figure out if it applies in this case or not.

So the first question is which parts of my CUP-wrapping project is actually embedded and which are not. Then we will know in which cases the CUP licence is wrapped by GPL. To answer it quickly; only `java-cup-runtime` must be embedded into your project. And here the GPL license wraps CUP license, by means of _combined work_ as stated in GPL.

For this reason I think your doubts are valid. If you were embedding original CUP jar, then it's fine. But you are encouraged by this project to embed `java-cup-runtime` so it forces you to make your project GPL. And this is not good. Adding GPL linking exception might help in this case, but I personally do not have any reason for insisting on GPL licence.

However, re-licencing is tricky. I would probably require to use the very same licence as the one CUP uses (see my "re-licencing" paragraph above).

I will probably keep GPL to the plugin itself, but re-licence the repackaged jars to the "CUP" license.

**Comment by vbmacher** [comment]
And I have figured out that actually licensing is correct - look at https://github.com/vbmacher/cup-maven-plugin/blob/master/java-cup-runtime/pom.xml and https://github.com/vbmacher/cup-maven-plugin/blob/master/java-cup/pom.xml.

The licenses part contains correct licence. So what needs to be fixed is:
- README.md
- Remove `<netbeans.hint.license>gpl20</netbeans.hint.license>` part
